# -*- coding: utf-8 -*-
"""Allclasses.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16UDnYmRJILPXtd3Ke1LFaKMhJFjiIl3p
"""

#list out the items
class All_functions():

  def subfields_inAI():
    list1 = ['Machine Learning','Neural Networks','Vision','Robotics','Speech Processing','Natural Language Processing']
    print("Sub-fields in AI are:")
    for i in list1:
      print(i)
  def odd_even():
    number = int(input("Enter a number"))
    if number % 2 == 0:
      print (number,"is Even")
      num_type = 'even'
    else:
      print(number," is odd")
      num_type = 'odd'
    return num_type
  #marriage eligibility
  def marriage_eligible():
    age = int(input("Enter your age : "))
    gender = input("Enter your gender : ")
    if (gender == 'male' and age< 21) or (gender == 'female' and age< 18):
      print("Not Eligible")
    else:
      print("Eligible")
  #find percent
  def percent(s1,s2,s3,s4,s5):
    total = s1+s2+s3+s4+s5
    percent = total/500 * 100
    return percent
  def triangle(h,b,h1,h2,b1):
    area = (h * b)/2
    perimeter = h1 + h2 + b1
    print("Area of triangle is",area)
    print("permimeter of triangle is",perimeter)
    return area,perimeter

"""# New Section"""

